### ISSUE TITLE
Running of spectralrao never end

### ISSUE THREAD

**Issue by dpoursanidis** [mattmar/spectralrao#1]
Dear Matt

Am running the following code at a PC with i7, SSD and 8GB RAM

> setwd("C:\\RaoIndexSamaria")
> ndvi<-raster('sample.tif')
> plot(ndvi)
> ndvi1<-2/255*ndvi-1
> plot(ndvi1)
> source("C:/RaoIndexSamaria/spectralrao2.r")
> rao10m<-spectralrao(input=ndvi1, distance_m="euclidean", window=5,
+                     shannon=TRUE, na.tolerance =1, nc.cores=1, 
+                     simplify=3,cluster.type="MPI", debugging=F)
Converting input data in an integer matrix...
Matrix check ok: 
Rao and Shannon output matrices will be returned

So far, even after 4 days of running, i don;t have any result. My NDVI data are at 10m (Sentinel 2) and cover an area of 40*50km.

I try on a smaller size area (3*3km) and even for that, after 48 hours of running i didn't have any result.

Any help is much appreciated

![spectralrao](https://user-images.githubusercontent.com/8640644/35734222-0db5ed98-0829-11e8-814d-3037833247f6.png)

**Comment by mattmar** [comment]
Hi Dimitri,

your analysis is on a lot of pixels, even the 3x3 matrix at a resolution of
10 meters means 3000*3000/10= 900,000 moving windows to work on.

Here the multicore option would help a lot, but I see you have problem with
Rmpi (and MPI) that is required for parallel jobs. Look at this page to
understand how to correctly install MPI for windows:
http://www.stats.uwo.ca/faculty/yu/Rmpi/

A couple of other optiond that would speed up your analysis are: 1) to use
*simplify=1* or 2) (obviously) resample your NDVI data at a different
resolution (100m?), but this may not be what you want.

Let me know if this helps at all!

Matteo

**Comment by dpoursanidis** [comment]
Thanks for the info Matteo

I will see the MPI issue and the *simplify=1* - resampling as well but i need the output at 10m - also, how can i set a timer in the code to monitor how much time is elapsed for the finalization of the analysis ?

D.

**Comment by mattmar** [comment]
Hi Dimitris,
you can wrap spectralrao in system.time() function

system.time(spectralrao(...))

Matteo
