### ISSUE TITLE
Add a user-defined distance matrix to spectralrao code

### ISSUE THREAD

**Issue by AggelikiD** [mattmar/spectralrao#2]
I was wondering if the spectralrao code may be modified to permit a user-defined distance matrix? This can be interesting for categorical variables where the euclidean (or other) distances cannot be computed.

**Comment by mattmar** [comment]
Hi Aggeliki, yes,
I've just added this possibility to the function. Now you can add a
personalised distance thorough the "distance_m" argument.

Please test the function and let me know if there is any problem.
Below a dummy example:

##Personalized distance
weir_distance <- function(x,y,...) {
return(cos(y-x)-sin(y-x))
}

ds1<-spectralrao(input=r1,distance_m=weir_distance,window=3,shannon=FALSE,na.tolerance=1)
ds2<-spectralrao(input=r1,distance_m="euclidean",window=3,shannon=FALSE,na.tolerance=1)

###Comparison
par(mfrow=c(1,2))
raster::plot(raster(ds1[[1]]),main="Weir_distance")
raster::plot(raster(ds2[[1]]),main="Euclidean_distance")

**Comment by AggelikiD** [comment]
Hi Matteo,

I now obtain an error message that didn't get with the previous version. It appears soon after I run the spectralrao : 

 Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  length of 'dimnames' [1] not equal to array extent 

Traceback:
5. array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),      NULL) else NULL)
4. as.matrix.default(x, ...) 
3. base::as.matrix(x, ...) 
2. as.matrix(rasterm) at spectral_RAO_new.R#62
1. spectralrao(ndvi, distance_m = "euclidean", window = 5, shannon = T, na.tolerance = 1, nc.cores = 2, simplify = 3, cluster.type = "SOCK", debugging = F)

For the ndvi I use a 0.1 degrees raster file from the NASA website

Let me know if you need more information from me
Thank you for your help!
Aggeliki

**Comment by AggelikiD** [comment]
Dear Matteo,

I managed to solve the error message by dividing the variables by their maximum values (so re-scaled values vary between 0 and 1). However re-scaling is not always optimal. What about categorical variables? I would like to use a user-defined distance matrix for a categorical variable. Is that still possible?

Thank you again for your help
Aggeliki

**Comment by mattmar** [comment]
Hi Aggeliki,
could you send me a minimal example with your NDVI data layer? It looks
like you are using a vector and not a matrix-like object as input.

Concerning the categorical variables, Rao is calculated "categorically" as
this index calculates the distance between two pixel values, which are
treated as "categories". Therefore I do not see the problem with inputting
a "categorical" matrix. Again, can you send me a minimum example where you
illustrate your exercise?

Thanks,
Matteo
