### ISSUE TITLE
Problem (parallel)

### ISSUE THREAD

**Issue by FrankVal** [mattmar/spectralrao#3]
Hi,

I would to express my problem regarding the spectralrao function.
I have the difficulty to compute this function on my study area in a normal way (very fine pixel grain and remarkable study area extension). Therefore, the only chance to compute the function is throughout the parallel processing. However, when i sett the funtion by defult with the MPI option, the function take indetermined time to create the selected number of clusters. It is normal?

Thank you in advance,

Francesco.

I have a 64 bit Linux operating system: Ubuntu (16.04.01) SMP

**Comment by mattmar** [comment]
Hi Francesco,
I've just seen your message, sorry.

Are you running the code on a distributed memory server (i.e., multiple nodes network baed cluster computer)?

I've had the same problem some time ago, MPI could not spawn the jobs and just hanged forever. If this is the case, it may be an issues linked with firewalls or the very installation of Rmpi or snow, but it seems to be a rather murky problem. Check this post:

http://r.789695.n4.nabble.com/R-snow-s-makeCluster-hanging-using-Rmpi-td811975.html

Let me know whether you found a solution or not
